### ISSUE TITLE
Issue with createdAt immutability after updating to v6

### ISSUE THREAD

**Issue by vtrphan** [Automattic/mongoose#10807]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I'm getting this error after updating to v6
`
TypeError: Invalid schema configuration: Trueis not a valid type at pathcreatedAt.immutable. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
`
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I expect no error just like the case with v5
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 14
Mongoose: 6.0.8

Please help

**Comment by sean-daley** [comment]
Looks like the same (or similar) issue described here https://github.com/Automattic/mongoose/issues/10761 which seems to be fixed in mongoose 6.0.8.

**Comment by vtrphan** [comment]
so i've updated to 6.0.8 and the problem still persists

**Comment by sean-daley** [comment]
Actually, sorry. The person that submitted that defect was able to resolve the problem on their side so nothing was actually changed in mongoose to resolve it.

**Comment by vtrphan** [comment]
Please advise how i can solve this problem. Looks like that issue also has the "bug" tag, so i assume this is a bug on mongoose's side?

**Comment by IslandRhythms** [comment]
Modify the script below to demonstrate your issue

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({ name: String, age: Number}, {timestamps:true});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017/', {useNewUrlParser: true,
    useUnifiedTopology: true,});
    await mongoose.connection.dropDatabase();

    await Test.create({name: 'a', age: 1});
    await Test.create({name: 'b', age: 2});
    await Test.create({name: 'c', age: 3});
    console.log(await Test.find())
    
}

run();
```

**Comment by vtrphan** [comment]
i'm using discriminator with timestamps: true in nestjs (via nestjs/mongoose package), and got the following error 
`TypeError: Invalid schema configuration: `True` is not a valid type at path `createdAt.immutable`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.`

**Comment by vkarpov15** [comment]
@vtrphan you do need to specify `timestamps: true` to get timestamps in child schemas.

Without a code sample that demonstrates this issue, we're unlikely to be able to fix this issue.

**Comment by vtrphan** [comment]
@vkarpov15 i have tried to recreate the issue. It can be found here. Run with yarn start
[https://codesandbox.io/s/agitated-mountain-ibg1m?file=/src/core.module.ts](url)

**Comment by vkarpov15** [comment]
I took a closer look and the issue is that you need to do `@Prop({ type: Date })` instead of `@Prop(Date)`. `@Prop(Date)` for some reason ends up registering a `type` property on `Date` equivalent to `Date.type = Date;`, which confuses Mongoose into thinking that `createdAt` is a nested property rather than a date.

We fixed this issue in b21a3d2, and will ship the fix in v6.0.13. In the meantime, just use `@Prop({ type: Date })`

**Comment by vtrphan** [comment]
@vkarpov15 so i took your advice and changed @Prop(Date) to @Prop({ type: Date}), but the error still persists?
See update version here:
https://codesandbox.io/s/fervent-water-r8siz?file=/src/user.schema.ts

Please advise

**Comment by vtrphan** [comment]
@vkarpov15 thank you for the advice. Had it working now. Thanks for your fix.
