### ISSUE TITLE
Could not find path in Schema while using arrayfilters

### ISSUE THREAD

**Issue by Augustya-sharma** [Automattic/mongoose#11390]
``` js
import {Schema, model} from 'mongoose'



const EmployeeSchema = new Schema({
    employeeCode: {
        type: String,
    },
    name: {
        type: String,

    },
    appraisal: {
        status: {
            type: String,
            enum: ["not started", "in progress", "completed", "not started", "self rating"],
            default: "not started"
        },
        objective_group: [{
            name: {
                type: Schema.Types.ObjectId,
                ref: "ObjectiveGroup",
                required: true
            },
            value: {
                type: Number,
            },
            objective_type: [{
                name: {
                    type: Schema.Types.ObjectId,
                    ref: "ObjectiveType",
                    required: true
                },
                value: {
                    type: Number,
                },

                objective_description: [{
                    name: {
                        type: Schema.Types.ObjectId,
                        ref: "ObjectiveDescription",
                        required: true
                    },
                    value: {
                        type: Number,
                    },
                    ratings: {
                        type: {
                            type: Schema.Types.ObjectId,
                            ref: "Ratings",

                        }
                    },

                }],
                training_recommendation: {
                    type: Schema.Types.ObjectId,
                    ref: 'TrainingRecommendation'
                },
                other_recommendation: {
                    type: Schema.Types.ObjectId,
                    ref: 'OtherRecommendation'
                },
            }],
        }],
    },
})

export default model('Employee', EmployeeSchema)
```

This is my Schema and I am trying to update value field in objective_group in  appraisal section 

```js
const updateValue = asyncHandler(async (req: Request, res: Response) => {

    const {id, rating} = req.body

    const employee = await Employee.findOneAndUpdate({
            "_id": "6204935ebca89023952f2da9",
        },
    {
            $set: {
                "appraisal.$[objective_group].value": 123
            }
        },
        {

            arrayFilters: [
                {
                    'objective_group._id': new mongoose.Schema.Types.ObjectId("6207ec6a8bfc1226d3f36fb1")
                }
            ]
        }
    )
    res.status(StatusCodes.OK).json({
        employee
    });
})
```

here is the code

**What is the current behavior?**
 Error: Could not find path "appraisal.0._id" in schema

I am getting this error 

**What is the expected behavior?**

it should update value field in objective_group

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
"mongoose": "^6.1.4",
node : v16.13.1

**Comment by IslandRhythms** [comment]
do `$set: {"appraisal.objective_group.0.value": 123}` instead

**Comment by Augustya-sharma** [comment]
Thanks a lot for the help this issue is resolved now But I am facing this error now 
`CastError: Cast to ObjectId failed for value "{ rate: new ObjectId("620b1b27b7c3b5a4a1eac528") }" (type Object) at path "_id" for model `
I even tried to add id directly from mongodb still I am getting this error

**Comment by Augustya-sharma** [comment]
Thanks a lot for the help this issue is resolved now. 
I have one question. I am stuck in a scenario where where I am populating rating scale description and it is ref ratings. What I want is when I populate my rating scale description it should also populate me value of the ratings 

```js
import {model, Schema} from "mongoose";

const RatingsSchema = new Schema( {
    rating: {
        type: Number,
        required: true
    },
})

export default model("Ratings", RatingsSchema);
```
This is my rating schema

```js

import {model, Schema} from "mongoose";

const RatingScaleDescriptionSchema = new Schema( {

    rating: {
        type: Schema.Types.ObjectId,
        ref: "Ratings",
        required: true
    },
    rating_scale: {
        type: String,
        required: true
    },
    definition: {
        type: String,
        required: true
    }
})

export default model("RatingScaleDescription", RatingScaleDescriptionSchema);
```

**Comment by IslandRhythms** [comment]
What does the query look like?

**Comment by darko55** [comment]
> do `findOneAndUpdate({_id: entry._id}, {$set: {"appraisal.objective_group.$[index].value": 123}}, {arrayFilters: [{'index._id': entry.appraisal.objective_group[0]._id}]});` instead

I tried to use this with updateMany, and update methods but it doesn't work. Is there any way to update many records with arrayFilter?

**Comment by TimMTech** [comment]
I can not believe their is still an issue with arrayFilters.  Come on guys, it has been almost 5 years.
