### ISSUE TITLE
.populate() does not work from a base schema, using discriminators, when the related collection is defined in the polymorphic child.

### ISSUE THREAD

**Issue by ericsaboia** [Automattic/mongoose#2719]
**mongoose version**: "^3.8.19"
**related to**: https://github.com/LearnBoost/mongoose/pull/1647

When you use discriminators, and want to query from the base schema, populating some related collection, which was defined in the polymorphic child schema, the query runs, but the result goes without the related population objects.

Example: 

```javascript
var mongoose = require('mongoose')
  , Schema = mongoose.Schema
  , util = require('util')
;

function BaseSchema() {
  Schema.apply(this, arguments);
  this.add( { name: String } );
}

util.inherits(BaseSchema, Schema);

var EventSchema = new BaseSchema();

var ConversionEvent = new BaseSchema({
  owner: { type: Schema.Types.ObjectId, ref: 'User', required: true }
});

var Base = mongoose.model('Event', EventSchema),
var Conversion = Base.discriminator('Conversion', ConversionEvent);

Conversion.create({
  name: 'test',
  owner: user._id
}, function (err, conversion) {

  Base.find().populate('owner').exec(function (err, bases) {
    // Owner object isen't attached
    console.log(bases); 
  });

});
```

**Comment by vkarpov15** [comment]
Hmm can you let me know what `EventSchema` looks like? Makes it much easier for me when I can just run your repro example as is.

**Comment by ericsaboia** [comment]
It's just an instance of the BaseSchema, I've updated the example.

**Comment by vkarpov15** [comment]
@ericsaboia this is by design. The schema underlying `Base` doesn't have an owner field, so `.populate('owner')` is invalid. `Conversion.find().populate('owner')` works as intended.

**Comment by ericsaboia** [comment]
Are you sure? because even when you query by the Base model, the returned object it's a instance of its child, and contains all the child fields:

For example:

```javascript
Base.find({}, function(err, events) {
    expect.ok(events[0] instanceof Base);       // true
    expect.ok(events[0] instanceof Conversion);       // true
   console.log(events[0].owner) // Owner ObjectId
});
```

So in my opinion it's worth the implementation.

**Comment by vkarpov15** [comment]
True, but when you call `populate()` it explicitly uses the base model and so doesn't know about 'owner'. It's a quirk, but one that makes sense IMO. What's your use case?

**Comment by ericsaboia** [comment]
It's a feed on a social app. My base model it's called Activity, and then I have a lot of specialised types of Activity (checkin, post, promotion, and so on)

Some of my Activity's children have specific relations, so it's no declared at the base model (Activity).

At my feed service, I need to return a list of all kind of activities, with the populates necessary to fill the client. 

Ps: the result is cached, that's why I decided to keep the call to "populate" instead of copy the necessary fields from the related collections.

**Comment by vkarpov15** [comment]
So in 3.x there's no way to populate from multiple models - one populate() call <=> one model. @chetverikov added the ability to populate from multiple models into 4.x so this may be more feasible now. I'll re-open this issue and see how feasible it is for a future release.

**Comment by diegodfsd** [comment]
Hi @vkarpov15 

I'm with the same problem but i saw that you close the issue this means that now should be possible populate a child of a specialisation?

**Comment by vkarpov15** [comment]
Yep see PR #2773 courtesy of @chetverikov

**Comment by diegodfsd** [comment]
Well,

I'm using Mongoose 4.0.1 and I can't populate a collection in one specialisation.

```
'use strict';

const Mongoose = require('mongoose'),
      Util = require('util');

function BaseSchema() {
  Mongoose.Schema.apply(this, arguments);

  this.add({
    name     : { type: String, required: true },
    date     : { type: Date, required: true },
    period   : { start : { type: String, required: true },
                 end   : { type: String, required: true } 
               }
  });
}

Util.inherits(BaseSchema, Mongoose.Schema);

let Event = new BaseSchema({});


module.exports = {
  schema: BaseSchema,
  model: Mongoose.model('Event', Event)
};
```

```
'use strict';

const Mongoose = require('mongoose'),
      Event = require('./event');

let Talk = new Event.schema({ 
  pin            : { type: String, required: true, index: { unique: true } },
  totalAttendees : { type: Number },
  speakers       : [{ type: Mongoose.Schema.Types.ObjectId, ref: 'Speaker' }],
  surveys        : [{ type: Mongoose.Schema.Types.ObjectId, ref: 'Survey' }],
  questions      : [{ type: Mongoose.Schema.Types.ObjectId, ref: 'Question' }]
});

module.exports = Event.model.discriminator('Talk', Talk);
```

Here is how I'm trying using populate unsuccessfully.

```
const  Event = require('./../models/event');

Event.find({}).populate('surveys').exec(function(err, events) {
  if (err) {
    console.dir(err);
  }
  console.dir(results[0].surveys); // this always returns undefined same when there is some item in the collection
});
```

I can't see where is my mistake or if the fix did not work.

**Comment by chetverikov** [comment]
Oh +( Forgive me please. 
![I made a mistake](http://lamcdn.net/lookatme.ru/post_image-image/VeOyxUhEsSIWvRxWk2_U3w-article.png)
Indeed, I made a mistake and wrote two lines incorrectly +( But I already corrected this problem! 
**https://github.com/Automattic/mongoose/pull/2825**
![corrected](http://lamcdn.net/lookatme.ru/post_image-image/_ZRe6BXbfxGg9SK98bOzMA-article.png)

**Comment by diegodfsd** [comment]
Do you will release a new version with this fix?

**Comment by ericsaboia** [comment]
cheers @chetverikov!

**Comment by diegodfsd** [comment]
No problem @chetverikov

**Comment by aforty** [comment]
I'm still having an issue with this, or perhaps I'm just doing something wrong. I also have the context of a social app with `Activity`, and then specific cases like `ActivityLiked` and `ActivityCommentMentioned`. I'm using version `4.4.12`.

When I `find()` and then `populate()`, it will not populate some fields. I can't give more detail than that as I haven't really fun it to be predictable in any way. It does seem like it's the field that is not present in another, fields that overlap seem to always populate fine.

`Activity`
```
var ActivitySchema = new mongoose.Schema(
  {
    user: { type: Number, ref: 'User', required: true, index: true },
    activityAt: { type: Date, required: true, default: Date.now },
  },
  {
    collection: 'Activities',
    discriminatorKey: 'type',
  }
);
```

``
```
let ActivityLiked = Activity.discriminator('Liked', new mongoose.Schema({
  from: { type: Number, ref: 'User', required: true },
  item: { type: Number, ref: 'Item', required: true },
}, { discriminatorKey: 'type' }));
```

`ActivityCommentMentioned`
```
let ActivityCommentMentioned = Activity.discriminator('CommentMentioned', new mongoose.Schema({
  from: { type: Number, ref: 'User', required: true },
  comment: { type: Number, ref: 'ItemComment', required: true },
  item: { type: Number, ref: 'Item', required: true },
}, { discriminatorKey: 'type' }));
```

Then I pull the code and attempt to populate it:
```
let items = await Activity
  .find({ user: req.user._id })
  .sort({ activityAt: -1 })
  .limit(30)
  .populate('from item comment');
```

Then the `comment` field will sometimes not be populated on `CommentMentioned` types. Everything else is populated as expected (maybe because they overlap between both discriminators?)
