### ISSUE TITLE
Date allows empty strings

### ISSUE THREAD

**Issue by eloytoro** [Automattic/mongoose#3134]
I've encountered an issue with the Date defined in mongoose.
It seems as if the Date type allows the user to save empty strings '' into the database, passing validation.
Doesn't make much sense to me.
Shouldnt it turn the value to null or throw a validation error?
I've added the test, but I'm not sure which would the correct behaviour be.

```javascript
user.birthday = '';
user.save(callback); // doesn't fail validation

/* ... */

console.log(user.birthday) // outputs empty string
```

**Comment by vkarpov15** [comment]
Hmm @eloytoro looks like the tests pass in master with no changes. Can you try upgrading to 4.1.1 and see if you still get this issue?

**Comment by eloytoro** [comment]
Well It looks like the issue was resolved somewhere along the way, because the test failed at the time and it doesn't now.
Merging the PR wouldnt hurt

**Comment by vkarpov15** [comment]
Already added a corresponding test. And the test failed in travis because of a timeout, you weren't calling `done()`

**Comment by eloytoro** [comment]
Well thats embarassing, however I did manage it to fail this time, please re-check the test

**Comment by vkarpov15** [comment]
That's because `.validate()`'s error type is 'ValidationError', not 'ValidatorError'. There's a subtle difference; a ValidationError has a one-to-many relationship with ValidatorErrors, which represent errors validating a single path. `schematype.doValidate()` gives you a ValidatorError because it validates a single path, `validate()` returns a ValidationError because it validates the whole document.

**Comment by alexmingoia** [comment]
This is not fixed. It looks like this commit changed the date cast function to return an empty string: https://github.com/Automattic/mongoose/commit/0ac0596368394edec115a47fb78d148f67ea29af

**Comment by eloytoro** [comment]
:shipit:

**Comment by vkarpov15** [comment]
@alexmingoia please provide a code example of the behavior you're seeing.
