### ISSUE TITLE
Performance regression from 4.5.10 to 4.6.2

### ISSUE THREAD

**Issue by lcalvy** [Automattic/mongoose#4690]
Hi,

We have bump mongoose from 4.5.10 to 4.6.2.
Our application have began to be unresponsive du to a huge processor usage

![image](https://cloud.githubusercontent.com/assets/937507/20050439/a374d0ca-a4c9-11e6-9b9a-8c3d0cc097cb.png)

A lot of 500 and 503 errors page appears

![image](https://cloud.githubusercontent.com/assets/937507/20050446/b0f04b4e-a4c9-11e6-95b2-50e981313d96.png)

And global response time was degradated.
![image](https://cloud.githubusercontent.com/assets/937507/20050452/b6106a6e-a4c9-11e6-963c-0e7bfa1d6c55.png)

After restoring to 4.5.10

cpu usage become normal again

![image](https://cloud.githubusercontent.com/assets/937507/20050950/a10d193e-a4cc-11e6-9806-3b7e2bdd5cf9.png)

* nodejs: 6.5.0
* mongodb: 3.0.8 with ssl and replica

Regards

**Comment by paton** [comment]
We're also experiencing degraded performance on the latest version, although we haven't pinpointed the version number.

Do you happen to be running a lot of `findOneAndUpdate` queries? We've been having issues with these (causing mongo `bytes out` network usage to go from 5-10 mb/s to maxing out and flatlining at 236 mb/s - we resolved this by modifying our `findOneAndUpdate` query a bit but still not sure of the cause).

We suspect there's also a bug with readPreference #4670. Do you make heavy use of secondaries for reads?

**Comment by loris** [comment]
This is concerning, what about `4.6.6`?

**Comment by vkarpov15** [comment]
Please provide some code samples. I don't know what your application does if you don't tell me :)

**Comment by kfiroo** [comment]
@lcalvy @paton Hey guys, did you try the latest releases? `4.7.0` / `4.7.1`?
Is this still the case?

Are you using still `4.5.10` for now?

**Comment by lcalvy** [comment]
Hi,

yes we are still using 4.5.10
We have don't test 4.7.1.
I will try to test next week.

@vkarpov15 we are doing CRUD operation, no agregation or map reduce or other complexe operation.

**Comment by kfiroo** [comment]
@lcalvy I've experienced strange things with 4.7.1 in production.
Requests to the DB would never return and requests fail on timeout.
I reverted ti 4.5.10 and the issue is gone.
Maybe related?

**Comment by randypuro** [comment]
I'm not sure it's related, but I've noted that on 4.7.1, the connections are now getting a default 30000ms `socketTimoutMS`; whereas previously (on 4.5.10), it would not have a default. Saw similar issues as @kfiroo seemingly triggered by those socket timeouts on really slow queries, and wondered if that in turn is triggering some sort of connection reuse/pooling problem?

**Comment by jus101** [comment]
Same issues here:
- connection to replica set takes 30s (but does connect)
- after working for a while (~ 20 queries), simple find queries begin blocking and not responding

Downgraded to 4.5.4 and everything working fine.

Might be something to do with the mongodb driver?

**Comment by djanowski** [comment]
I believe this is a duplicate of https://github.com/Automattic/mongoose/issues/4513.

**Comment by djanowski** [comment]
Does anyone have a full self-contained example we can look at?

**Comment by djanowski** [comment]
Looks like @randypuro hit the nail on the head.

I was able to reproduce the issue by creating a script that runs non-trivial queries concurrently. Setting _any_ timeout causes the CPU/memory issues, and the connection eventually drops. Disabling timeouts (by passing 0) makes everything work well.

We deployed 4.7.7 with `socketTimeoutMS: 0` a couple of hours ago and haven't seen any issues so far.

**Comment by loris** [comment]
Still seeing performance regression in our app: 

`v1269` is `mongoose@4.5.10` with `socketTimeoutMS: 1800000` → response time is ~25ms
`v1270` is `mongoose@4.7.7` with `socketTimeoutMS: 0` → response time is ~70ms
`v1271` is `mongoose@4.5.10` with `socketTimeoutMS: 1800000` → response time is ~25ms

![](https://dl.dropboxusercontent.com/spa/tqch4axi0t55dpk/lyj3g_9q.png)

**Comment by vkarpov15** [comment]
So 4.8.0 includes some major performance improvements for document arrays re #2754, but won't be out until next week. Please give that a shot once its released.

Also, would be very helpful to see some code samples. "My endpoints are slow in version X" is not an actionable bug report.

**Comment by magaliegimenes** [comment]
+1 for this issue. 
I am migrating my API from my old server on mongoose 4.4.13 to a new server on mongoose 4.9.7 and for this query: 
`MyModel.find({$or: [{fied1: value}, {field2: value}, {field3: value}]}).lean(true).select(outputFieldsString).exec()`
I have experienced a decrease in performance. 
I get from this request 2400 documents and it takes 1200ms on my old server against 1600ms on the new one. When i downgraded mongoose version to 4.5.10 on my new server, i got the response in less than one second.
I have seen that mongodb library went from 2.1 to 2.2 between 4.5 and 4.6 mongoose version but i don't if this is related.
Do not hesitate to ask for more details.

**Comment by vkarpov15** [comment]
@magaliegimenes can you clarify what the output of that query is and show your schema?

**Comment by magaliegimenes** [comment]
This is what my schema looks like: 
`const mySchema = new Schema({
  newId: { type: String, required: true, trim: true, index: true, unique: true },
  userId: { type: String, required: true, trim: true }, // Owner uuid
  name: { type: String, required: true, trim: true },
  parent: { type: String, trim: true },
  type: { type: String, required: true, trim: true },
  simpleObjectArray: { type: Array },
  description: { type: String },
  wasTaken: { type: Boolean, default: false },
  label: { type: String }, 
  users: {
    viewers: { type: Array },
    contributors: { type: Array }
  },
  stringArray: { type: Array },
  simpleObject: Schema.Types.Mixed,
  serverUrl: { type: String },
  key: { type: String },
  children: { type: Array },
  objectRefs: { type: Array },
  deleted: { type: Boolean, required: true, default: false },
  sweats: { type: Array },
  sweatsDeleted: { type: Array },
  glasses: { type: Array },
  glassesDeleted: { type: Array },
}, { strict: false, timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' } });
`

In the select parameter we have:
`const PROJECTION = '-_id -__v -updated_at -created_at -sweatsDeleted -children -deleted -glasses -glassesDeleted -objectRefs -simpleObject.attachments -simpleObject.array -simpleObject.array2 -simpleObject.array3 -simpleObject.forwards -simpleObject.deleted -simpleObject.noValidate -simpleObject.updated_at -simpleObject._id -simpleObject.userId -simpleObject.class -simpleObject.description -simpleObject.parent -simpleObject.created_at -simpleObject.__v -simpleObject.sweat -simpleObject.time'; `
