### ISSUE TITLE
insertMany() doesn't return a promise

### ISSUE THREAD

**Issue by jordykoppen** [Automattic/mongoose#5409]
Currently when I try and insertMany on my Model it won't return anything.
`node  v7.9.0`
`mongoose v4.11.0`
`mongoDB v2.2.29`

code:
```
Option.insertMany(options).then((err, docs) => {
    console.log(docs);
    console.log(err);
  })
```

No logs are present in the console.

**Comment by lmanco** [comment]
This is happening to me as well for the same versions listed above. Not just for insertMany, but for find and findOne as well. The problem is not present if I downgrade to mongoose v4.10.0.

**Comment by vkarpov15** [comment]
Below script works without error for me. Please modify the script to reproduce your issue.

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5409`;

mongoose.set('debug', true);

exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
  });


function exec() {
  return co(function* () {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${GITHUB_ISSUE}`)

    const Test = db.model('Test', new mongoose.Schema({ name: String }));

    yield Test.insertMany([{ name: 'test' }]).then(() => ({ ok: 1 }));
  });
}
```

**Comment by vkarpov15** [comment]
There was an issue with useMongoClient in 4.11.0 that was fixed with 4.11.1 that explains what you described. Please upgrade to 4.11.1.

**Comment by varunjayaraman** [comment]
@jordykoppen can you confirm whether or not it works on > 4.11.1?

**Comment by jordykoppen** [comment]
@varunjayaraman Will give it a try later on today.

**Comment by varunjayaraman** [comment]
@jordykoppen any update?

**Comment by nmaxcom** [comment]
To me it's still an issue, I'm using mongoose 5.2.8.

Debugging seems to show that you are forced to use a callback within insertMany() parameters, instead of being able to use .then() and .catch() as it should allow.
