### ISSUE TITLE
Remove jest jsdom warning

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#5593]
https://github.com/Automattic/mongoose/commit/c1de420f34b1cbdce888d7481b412080a77070b0#commitcomment-23791131

**Comment by vkarpov15** [comment]
Fixed in https://github.com/Automattic/mongoose/commit/9c487909a21a128dae8ed434cf3bd4630129d64e

**Comment by xilaraux** [comment]
It's still relevant for version `5.3.13`.
Jest test environment: `node`.

![image](https://user-images.githubusercontent.com/17703730/48947760-ed1c5a00-ef3a-11e8-8a58-6de2b21cf157.png)

**Comment by xilaraux** [comment]
It's seems still relevant.

```
"jest": "^22.4.4",
"mongoose": "^5.3.13",
```

Jest testing environment is `node`.

![image](https://user-images.githubusercontent.com/17703730/48947919-7af84500-ef3b-11e8-8eb9-600c5d9ff258.png)

**Comment by gregorybellencontre** [comment]
@xilaraux Maybe you resolved it since, but for those who still have this issue, make sure you didn't declare "window" object in globals in your Jest configuration.
The warning only appears when both Jest and window are defined.

**Comment by vkarpov15** [comment]
@gregorybellencontre do you know of a better way to check the jest test environment? I might be missing something - the spirit of this warning is avoiding the jsdom test environment, not the window global specifically
